In [108]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

In [136]:
train_features_data=pd.read_csv('train_features.csv')
train_labels_data=pd.read_csv('train_labels.csv')
test_features_data=pd.read_csv('test_features.csv')
# add labels with matching pid to features
labels_copied = pd.DataFrame()
labels_copied = labels_data.loc[labels_data.index.repeat(12)]
labels_copied = labels_copied.drop(columns=['pid'])
labels = train_labels_data.drop(columns=['pid'])
LABELS1 = ['LABEL_BaseExcess', 'LABEL_Fibrinogen', 'LABEL_AST', 'LABEL_Alkalinephos', 'LABEL_Bilirubin_total',
         'LABEL_Lactate', 'LABEL_TroponinI', 'LABEL_SaO2',
         'LABEL_Bilirubin_direct', 'LABEL_EtCO2']
LABELS2 = ['LABEL_Sepsis']
LABELS3 = ['LABEL_RRate', 'LABEL_ABPm', 'LABEL_SpO2', 'LABEL_Heartrate']

## Subtask 1

In [144]:
X = train_features_data.drop(columns=['pid', 'Time']).reset_index(drop=True).fillna(train_features_data.mean())
y = labels_copied[LABELS1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

TEST_X = test_features_data.drop(columns=['pid', 'Time']).reset_index(drop=True).fillna(test_features_data.mean())

In [146]:
clf=RandomForestClassifier(class_weight='balanced')
clf.fit(X_train, y_train)
y_pred_proba=clf.predict_proba(X_test)
err=np.empty(10)
list_proba=list()
for i,label in enumerate(LABELS1):
    err[i]=roc_auc_score(y_test[label], y_pred_proba[i][:,1])
    list_proba.append(y_pred_proba[i][:,1])
display(err)
display(list_proba)

array([0.74774497, 0.58494293, 0.59480264, 0.59759122, 0.59616511,
       0.62442237, 0.68243791, 0.66054309, 0.60079126, 0.81829768])

[array([0.73038029, 0.65      , 0.41      , ..., 0.21      , 0.16      ,
        0.22      ]),
 array([0.93133338, 0.09      , 0.06      , ..., 0.02      , 0.03      ,
        0.02      ]),
 array([0.99674711, 0.11      , 0.15      , ..., 0.25      , 0.24      ,
        0.28      ]),
 array([0.99674027, 0.1       , 0.15      , ..., 0.22      , 0.23      ,
        0.3       ]),
 array([0.99681662, 0.11      , 0.14      , ..., 0.22      , 0.23      ,
        0.28      ]),
 array([0.9653894, 0.26     , 0.23     , ..., 0.18     , 0.1      ,
        0.25     ]),
 array([0.70798525, 0.02      , 0.05      , ..., 0.1       , 0.04      ,
        0.05      ]),
 array([0.99383216, 0.65      , 0.37      , ..., 0.19      , 0.16      ,
        0.26      ]),
 array([0.93945573, 0.        , 0.01      , ..., 0.        , 0.        ,
        0.01      ]),
 array([0.23663882, 0.        , 0.02      , ..., 0.05      , 0.03      ,
        0.03      ])]

In [133]:
TEST_y_pred=clf.predict_proba(TEST_X)
display(TEST_y_pred[0][:,1])

array([0.13784386, 0.16      , 0.14      , ..., 0.17      , 0.11      ,
       0.14      ])

In [185]:
TEST_y_pred_proba=np.empty(int(len(TEST_y_pred[0][:,1])/12))
counter=0
for splits in np.split(np.array(TEST_y_pred[0][:,1]), int(len(TEST_y_pred[0][:,1])/12)):
    TEST_y_pred_proba[counter]=splits.mean() 
    counter=counter+1
display(counter)

12664

In [176]:
y_test_reduced=y_test['LABEL_BaseExcess'][0:len(y_test['LABEL_BaseExcess']):12]
display(y_test_reduced.shape)
#roc_auc_score(y_test[label], y_pred_proba[i][:,1])

(3799,)

In [177]:
y_pred_proba_reduced=np.empty(int(len(y_pred_proba[0][:,1])/12))
counter=0
for splits in np.split(np.array(y_pred_proba[0][:,1]), int(len(y_pred_proba[0][:,1])/12)):
    y_pred_proba_reduced[counter]=splits.mean() 
    counter=counter+1
display(y_pred_proba_reduced.shape)

(3799,)

In [196]:
arr=[1,2,3,4,5,6]
for splits in np.split(np.array(arr), int(len(arr)/2)):
    display(splits.mean())


1.5

3.5

5.5

In [178]:
roc_auc_score(y_test_reduced, y_pred_proba_reduced)

0.8567692716897186

### Subtask 2

In [135]:
display(list_proba[0][0:100])

array([0.16      , 0.26      , 0.23      , 0.35      , 0.12      ,
       0.73629986, 0.06      , 0.43      , 0.19      , 0.56      ,
       0.28      , 0.71      , 0.24      , 0.63      , 0.25      ,
       0.56386487, 0.28      , 0.4       , 0.26      , 0.07      ,
       0.13      , 0.56      , 0.19      , 0.21      , 0.08      ,
       0.8       , 0.65      , 0.01878386, 0.26      , 0.21      ,
       0.17      , 0.53      , 0.18      , 0.1       , 0.40480885,
       0.28      , 0.2       , 0.08      , 0.41      , 0.41      ,
       0.63450253, 0.72      , 0.46      , 0.43      , 0.19      ,
       0.08      , 0.12      , 0.14      , 0.56386487, 0.32      ,
       0.43      , 0.90278915, 0.55      , 0.12      , 0.21      ,
       0.06      , 0.19      , 0.69      , 0.85      , 0.13      ,
       0.86347815, 0.14      , 0.13      , 0.5       , 0.25      ,
       0.45      , 0.07      , 0.8582044 , 0.26      , 0.33      ,
       0.46      , 0.33      , 0.57      , 0.64      , 0.76   

In [183]:
filename = 'sample.zip'
df_submission = pd.read_csv(filename)
for i,label in enumerate(LABELS1):
    # round classification labels
    df_submission[label]=TEST_y_pred_proba[i]
df_submission.to_csv('submission.csv',index=False, header=False)