In [1]:
#Special about this task:
#
# missing features and imbalanced classification, predicting rarely-occuring events

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier

#load dataset
train_features_data=pd.read_csv('train_features.csv')
labels_data=pd.read_csv('train_labels.csv')
#extract features with pandas groupby method
train_data=pd.DataFrame(train_features_data.groupby(['pid']).mean())
train=train_data.reset_index().drop(columns=['pid', 'Time']).fillna(train_data.mean()) #assumed that time plays no role on predictions
display(train)
#labels=labels_data.drop(columns=['pid'])
labels1 = labels_data[['LABEL_BaseExcess', 'LABEL_Fibrinogen', 'LABEL_AST', 'LABEL_Alkalinephos', 'LABEL_Bilirubin_total', 'LABEL_Lactate', 'LABEL_TroponinI', 'LABEL_SaO2', 'LABEL_Bilirubin_direct', 'LABEL_EtCO2']]
labels2 = labels_data[['LABEL_Sepsis']]
labels3 = labels_data[['LABEL_RRate', 'LABEL_ABPm', 'LABEL_SpO2', 'LABEL_Heartrate']]

Age      EtCO2        PTT        BUN   Lactate       Temp        Hgb  \
0      34.0  32.829817  38.801443  12.000000  2.383041  36.750000   8.566667   
1      86.0  32.829817  31.800000  32.000000  2.383041  36.000000  13.100000   
2      66.0  32.829817  34.600000   8.000000  2.383041  36.666667  10.550000   
3      66.0  32.829817  53.800000  32.000000  1.800000  37.166667  10.316667   
4      42.0  32.829817  38.801443  18.000000  2.383041  36.000000  10.748832   
...     ...        ...        ...        ...       ...        ...        ...   
18990  52.0  32.829817  25.800000  11.000000  1.700000  36.000000   9.500000   
18991  66.0  32.829817  38.801443  33.000000  2.383041  37.500000  11.200000   
18992  44.0  32.829817  38.801443  15.000000  2.383041  38.000000  12.400000   
18993  70.0  32.829817  38.801443  23.000573  2.383041  36.500000  10.748832   
18994  60.0  32.829817  38.801443  13.000000  2.383041  36.500000  14.400000   

            HCO3  BaseExcess      RRate  ...  Alkalinephos        SpO2  \
0      25.333333   -0.666667  17.000000  ...     96.675671  100.000000   
1      23.801594   -0.789992  18.000000  ...     96.675671   96.000000   
2      23.801594   -0.789992  14.636364  ...    130.000000   99.272727   
3      19.500000   -2.857143  15.833333  ...     96.675671   99.333333   
4      23.801594   -0.789992  17.181818  ...     96.675671   97.800000   
...          ...         ...        ...  ...           ...         ...   
18990  22.666667    0.000000  15.545455  ...     96.675671   96.181818   
18991  23.801594   -0.789992  16.909091  ...     96.675671   96.090909   
18992  24.000000   -3.500000  24.900000  ...     96.675671  100.000000   
18993  23.801594   -0.789992  15.500000  ...     96.675671   99.100000   
18994  23.801594   -0.789992  18.126663  ...     96.675671   96.000000   

       Bilirubin_direct    Chloride        Hct   Heartrate  Bilirubin_total  \
0              1.170195  112.000000  23.200000   77.083333         1.544023   
1              1.170195  105.925903  40.200000   59.000000         1.544023   
2              0.100000  105.925903  33.550000   72.545455         0.600000   
3              1.170195  113.500000  30.390000   87.333333         1.544023   
4              1.170195  105.925903  32.005177   81.181818         1.544023   
...                 ...         ...        ...         ...              ...   
18990          1.170195  106.000000  31.560000  108.272727         1.544023   
18991          1.170195  105.925903  34.600000   92.909091         1.544023   
18992          1.170195   97.000000  36.700000   99.100000         1.544023   
18993          1.170195  105.925903  32.005177   64.400000         1.544023   
18994          1.170195  105.925903  40.200000   68.000000         1.544023   

       TroponinI        ABPs        pH  
0       6.414359  114.500000  7.370000  
1       0.440000  131.181818  7.375355  
2       0.020000  125.454545  7.375355  
3       6.414359  100.666667  7.352857  
4       0.080000  204.545455  7.375355  
...          ...         ...       ...  
18990   6.414359   87.333333  7.330000  
18991   6.414359  165.000000  7.375355  
18992   6.414359  100.300000  7.300000  
18993   6.414359  110.500000  7.375355  
18994   6.414359  133.000000  7.375355  

[18995 rows x 35 columns]

## Subtask1

### Regression models

In [12]:
#Linear Regression model
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred=pd.DataFrame(model.predict(X_test))
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)
print(model.predict(X_test))
#y_pred.to_csv('prediction.zip', index=False, float_format='%.3f', compression='zip')
y_pred.to_csv('submission.csv', index=False, header= None)

0.3670680975661088
[[0.27277674 0.07701021 0.25395403 ... 0.24317755 0.04672681 0.07147905]
 [0.25462353 0.04259344 0.23347652 ... 0.25744897 0.05082636 0.04114712]
 [0.2724582  0.07844939 0.24926045 ... 0.2203056  0.04331503 0.05679011]
 ...
 [0.26386166 0.05133288 0.26701203 ... 0.24097621 0.04524302 0.06147501]
 [0.26618286 0.07113257 0.21848341 ... 0.20402182 0.03556564 0.06705919]
 [0.24175538 0.04973555 0.20991926 ... 0.21775481 0.04314602 0.0710091 ]]


In [13]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
X, y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0).fit(X, y)
y_pred=clf.predict_proba(X)
display(y_pred)

C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[9.81798885e-01, 1.82011004e-02, 1.43499227e-08],
       [9.71721788e-01, 2.82781823e-02, 3.00194617e-08],
       [9.85449423e-01, 1.45505647e-02, 1.22616229e-08],
       [9.76296778e-01, 2.37031826e-02, 3.95217425e-08],
       [9.85386872e-01, 1.46131162e-02, 1.18792868e-08],
       [9.70466976e-01, 2.95329508e-02, 7.31355450e-08],
       [9.86890591e-01, 1.31093893e-02, 1.98716082e-08],
       [9.76400810e-01, 2.35991622e-02, 2.74875030e-08],
       [9.79843687e-01, 2.01562825e-02, 3.05344325e-08],
       [9.69131799e-01, 3.08681693e-02, 3.14925519e-08],
       [9.76504394e-01, 2.34955873e-02, 1.91176405e-08],
       [9.75412640e-01, 2.45873167e-02, 4.36246785e-08],
       [9.74557642e-01, 2.54423370e-02, 2.13792130e-08],
       [9.91972830e-01, 8.02716625e-03, 3.87385241e-09],
       [9.88201051e-01, 1.17989458e-02, 2.79175236e-09],
       [9.86774747e-01, 1.32252408e-02, 1.27151873e-08],
       [9.88115246e-01, 1.18847450e-02, 9.14773174e-09],
       [9.81554758e-01, 1.84452

In [27]:
#Linear LassoCV Regression model
from sklearn.linear_model import LassoCV
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)

model = MultiOutputRegressor(LassoCV(alphas = np.linspace(0.1,100,100), fit_intercept=False, max_iter=300000, cv=10, random_state=0))
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

0.36682697387567126


In [28]:
#Knearest neighbour
from sklearn.neighbors import KNeighborsRegressor
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)
model = KNeighborsRegressor()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

0.40009475055732824


In [8]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

0.5263521551283064


In [ ]:
#Decision Tree with cross validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor
#from sklearn.model_selection import RepeatedKFold
#cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
kf = KFold(n_splits=10, random_state=0, shuffle=True)
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)
model = DecisionTreeRegressor()
result = cross_val_score(model, X_train, y_train, scoring='neg_root_mean_squared_error', cv = kf)
result = np.absolute(result)



In [15]:
#SVR
from sklearn.svm import LinearSVR
from sklearn.multioutput import MultiOutputRegressor
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)
model = MultiOutputRegressor(LinearSVR())
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: Conv

0.6374500646573907


C:\Users\Manue\anaconda3\envs\MLenv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


### Classifier models

In [10]:
from sklearn.linear_model import RidgeClassifierCV
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)

model = RidgeClassifierCV(cv=10)
model.fit(X_train, y_train)
#y_pred=model.predict(X_test)
print(model.predict(X_test)[0:20])
print(model._predict_proba_lr(X_test))
# err=np.sqrt(mean_squared_error(y_pred,y_test))
# print(err)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0.11249495 0.08698821 0.10991488 ... 0.10844697 0.0833467  0.08631727]
 [0.11186247 0.08425402 0.10894238 ... 0.11225211 0.08524785 0.08408117]
 [0.1133615  0.08787521 0.1101609  ... 0.10621745 0.08361958 0.08523684]
 ...
 [0.11163303 0.08417308 0.11206669 ... 0.10850341 0.08344665 0.08539107]
 [0.11429744 0.08838062 0.10767209 ... 0.10569842 0.08403066 0.08787437]
 [0.11177811 0.08642708 0.10735681 ... 0.10843585 0.08561927 0.08906605]]


In [29]:
#KNeighborsClassifier
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)
model = MultiOutputClassifier(KNeighborsClassifier())
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

0.44182492640887694


In [30]:
#DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels1, test_size=0.2, random_state=42)
model = DecisionTreeClassifier(random_state=0)
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

0.5289960294346954


## Subtask 2

In [32]:
#Linear Regression model
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels2, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

0.22870411765179602


In [27]:
y_pred[:,:]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Subtask3

In [33]:
#Linear Regression model
#split into train and test set
X_train, X_test, y_train, y_test = train_test_split(train, labels3, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
err=np.sqrt(mean_squared_error(y_pred,y_test))
print(err)

9.893299105311838


### help-functions provided for task 

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
X, y = load_breast_cancer(return_X_y=True)
clf = LogisticRegression(solver="liblinear", random_state=0).fit(X, y)
roc_auc_score(y, clf.predict_proba(X)[:, 1])

In [2]:
# suppose df is a pandas dataframe containing the result
#df.to_csv('prediction.zip', index=False, float_format='%.3f', compression='zip')