# Regression example

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
print(X.shape)
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.score(X,y)
reg.predict(np.array([[3,5]]))

(4, 2)


array([16.])

# Dummy Task

## Load dataset and split into training and test data

In [63]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
data=pd.read_csv('train.csv')
y=data['y']
train=data.iloc[0:10000,2:12]
X=np.asarray(train)
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)
X_train

array([[ -843.301229  , -1256.38774027,  1047.38577296, ...,
         1332.44821581,   423.46720879,  -645.77202346],
       [  755.76797286, -1144.05524309,  1223.02653854, ...,
        -1620.56683539,  1706.94220518,   810.20052812],
       [-2252.39262352,  -196.81080579,  -286.35003968, ...,
        -1349.30414002,   116.44328752,   108.69650503],
       ...,
       [-1327.16549386,  1396.78742682,  -128.77424569, ...,
          108.50559286, -1588.45675665,  1079.79921404],
       [   38.39310049, -1432.7731115 ,  1650.22135906, ...,
        -1695.19893906,   278.302674  ,   938.30121101],
       [ -100.23162706,  -400.52194375,  -284.82614596, ...,
         -274.00589113,  1589.4555108 ,   212.54964422]])

## Fit model

In [65]:
reg = LinearRegression().fit(X_train, y_train)
print(reg.score(X_train,y_train))
print(reg.coef_)
print(reg.intercept_)
y_pred = reg.predict(X_test)

1.0
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
-1.4210854715202004e-14


In [67]:
RMSE=np.sqrt(((y_pred - y_test) ** 2).mean())
RMSE

2.622148645633288e-13

## Load test dataset

In [68]:
test_data=pd.read_csv('test.csv')
test_data

Id           x1           x2           x3           x4           x5  \
0     10000  -483.797492  1288.057065  -129.878712  -198.078388  -334.487592   
1     10001  -316.407305    30.830556  -313.356726  -173.259184  -327.368719   
2     10002 -2448.558997  -561.988408   355.098820   634.378170  -392.450091   
3     10003  -942.120025   945.373015   140.910705  1753.565841  -347.223685   
4     10004  1752.366157  -597.550816  -466.491398 -1094.792276  -645.424882   
...     ...          ...          ...          ...          ...          ...   
1995  11995   -70.207810   328.849423  1006.084617   440.948562  -692.274282   
1996  11996 -1692.417164   968.971133  1371.423442  -144.224724   503.164492   
1997  11997   199.864648   261.345779  -127.986805  -298.503216  -364.240174   
1998  11998  -151.673157 -1425.199620  1070.922114   938.800763  1373.176372   
1999  11999   -97.089983   780.444250   221.081520    72.748763 -1484.861623   

               x6           x7           x8           x9          x10  
0     -391.443186  -612.406176  -676.523964  1327.229655  -448.695446  
1      944.368248  1122.017380   112.338731  1372.340221  2062.561842  
2     -813.156399  -232.873263   246.801210  -562.413197  -841.602015  
3    -1489.493408  -508.035412  1992.650031   555.461973 -1696.076948  
4     -202.154830   205.073469  -270.385827  -310.299496   362.212675  
...           ...          ...          ...          ...          ...  
1995   237.091043  -565.192046  1893.955311  1277.944394   789.953338  
1996  -228.219798   153.761541  1872.043587  2153.553632     6.797203  
1997 -1370.134911   769.662730  -517.182892    79.694141  1016.126607  
1998  -583.905998  -292.269529 -1206.766021 -1047.464871     7.588102  
1999   462.159812  1549.025158  2531.705492   -35.722034   173.200191  

[2000 rows x 11 columns]

In [69]:
submissiondf = pd.DataFrame()
submissiondf['Id']= test_data['Id']
submissiondf

Id
0     10000
1     10001
2     10002
3     10003
4     10004
...     ...
1995  11995
1996  11996
1997  11997
1998  11998
1999  11999

[2000 rows x 1 columns]

In [70]:
test=test_data.iloc[0:2000,1:11]
test=np.asarray(test)

## Predict over testdata

In [71]:
y_predict=pd.DataFrame(reg.predict(test))
y_predict

0
0     -66.002423
1     451.406504
2    -461.676417
3      40.501209
4    -126.744722
...          ...
1995  464.715255
1996  496.485334
1997  -35.135409
1998 -131.679185
1999  417.269155

[2000 rows x 1 columns]

In [72]:
submissiondf['y']=y_predict
submissiondf

Id           y
0     10000  -66.002423
1     10001  451.406504
2     10002 -461.676417
3     10003   40.501209
4     10004 -126.744722
...     ...         ...
1995  11995  464.715255
1996  11996  496.485334
1997  11997  -35.135409
1998  11998 -131.679185
1999  11999  417.269155

[2000 rows x 2 columns]

In [74]:
submissiondf.to_csv('submission.csv', index=False)